"""
build_universe.py
Finviz 무료 스크리너로 오늘의 후보군을 자동 수집.

Finviz 필터 역할: "거래 불가 쓰레기 제거"만 담당.
실제 RVOL / PM Gap / 촉매 필터링은 screener.py에서 처리.

필터 조건:
  - 주가       : $5 ~ $50
  - 시총       : Small ($300M) 이상
  - 평균 거래량 : 500K주 이상
  - 거래소     : NYSE, NASDAQ

제거된 조건 (전략과 충돌):
  - 20MA 위 (Price above SMA20) → 카탈리스트 당일 갭업 종목 놓침
  - 주간 상승 (Week Up)         → 눌려있다 터지는 최고 셋업 놓침

결과 → universe_today.txt (매일 덮어씀)

실행:
  python build_universe.py           # 기본 (상위 300종목)
  python build_universe.py --top 150 # 상위 150종목만
"""

import argparse
import sys
import os
from datetime import datetime

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))


def fetch_from_finviz(max_tickers: int = 150) -> list[str]:
    """Finviz 스크리너로 후보군 수집."""
    try:
        from finvizfinance.screener.overview import Overview

        foverview = Overview()
        # Finviz는 Exchange 필터를 단일값만 허용 → NASDAQ + NYSE 두 번 호출 후 합산
        tickers_all = []
        for exchange in ["NASDAQ", "NYSE"]:
            foverview.set_filter(filters_dict={
                "Price":          "$5 to $50",
                "Market Cap.":    "+Small (over $300mln)",
                "Average Volume": "Over 500K",
                "Exchange":       exchange,
            })
            df_ex = foverview.screener_view(order="Volume", ascend=False, verbose=0)
            if df_ex is not None and not df_ex.empty:
                tickers_all.extend(df_ex["Ticker"].tolist())

        if not tickers_all:
            return []

        # 중복 제거, 볼륨순 정렬은 이미 각 호출에서 됐으므로 순서 유지
        seen = set()
        tickers_dedup = []
        for t in tickers_all:
            if t not in seen:
                seen.add(t)
                tickers_dedup.append(t)

        print(f"  Finviz: {len(tickers_dedup)} matches (NASDAQ+NYSE) → using top {min(len(tickers_dedup), max_tickers)}")
        return tickers_dedup[:max_tickers]

    except ImportError:
        print("  finvizfinance not installed: pip install finvizfinance")
        return []
    except Exception as e:
        print(f"  Finviz fetch failed: {e}")
        return []


def fetch_fallback_manual() -> list[str]:
    """
    Finviz 실패 시 수동 백업 리스트.
    일주일에 한 번 직접 업데이트 권장.
    """
    return [
        # 바이오/헬스케어
        "ACAD","ADMA","ALKS","APLS","ARWR","BEAM","CLDX","CRSP","CYTK",
        "FOLD","IOVA","ITCI","MRTX","NVAX","PCVX","RCUS","RVMD","SAGE",
        "SRPT","TGTX","YMAB","KROS","LEGN",
        # 테크/소프트웨어
        "AMBA","APPN","BAND","BTBT","DOCN","FRSH","MGNI","MARA","OPEN",
        "PAYO","RIOT","STEM","TOST","VRNS","ZI","AGYS","CNXC","HCAT",
        # 소비재
        "BOOT","CVNA","ELF","GPRO","LOVE","PTLO","RMBL","SKIN","XPOF",
        "MODG","URBN",
        # 에너지/산업
        "AMRC","CLNE","COHU","CRK","DQ","FLNC","HUT","MTDR","SHLS",
        "SMR","VET",
        # 금융/기타
        "UPST","HIMS","CELH","SOFI","AFRM",
    ]


def save_universe(tickers: list[str], path: str = "universe_today.txt"):
    today = datetime.now().strftime("%Y-%m-%d %H:%M")
    with open(path, "w", encoding="utf-8", errors="replace") as f:
        f.write(f"# Auto-generated by build_universe.py  [{today}]\n")
        f.write(f"# {len(tickers)} tickers\n\n")
        for t in tickers:
            f.write(f"{t}\n")
    print(f"  Saved {len(tickers)} tickers → {path}")


def main():
    parser = argparse.ArgumentParser(description="Build today's screener universe")
    parser.add_argument("--top",    type=int, default=300, help="Max tickers to include")
    parser.add_argument("--output", type=str, default="universe_today.txt")
    parser.add_argument("--manual", action="store_true",
                        help="Use manual fallback list (skip Finviz)")
    args = parser.parse_args()

    print("\n" + "="*50)
    print("  Universe Builder")
    print("="*50)

    if args.manual:
        tickers = fetch_fallback_manual()
        print(f"  Manual list: {len(tickers)} tickers")
    else:
        print("  Fetching from Finviz...")
        tickers = fetch_from_finviz(args.top)
        if not tickers:
            print("  Falling back to manual list...")
            tickers = fetch_fallback_manual()

    save_universe(tickers, args.output)

    print(f"\n  Next step:")
    print(f"    python screener.py --universe {args.output} --verbose")
    print()


if __name__ == "__main__":
    main()
